# Generated by Django 5.2.11 on 2026-03-04 02:30

import cis.storage_backend
import cis.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('cis', '0045_alter_applicantcoursereviewer_unique_together_and_more'),
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('Inactive', 'Inactive')], default='Incomplete', max_length=30)),
                ('verification_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('account_verified', models.BooleanField(default=False)),
                ('account_verified_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdon', models.DateField()),
                ('status_changed_on', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved for FC review', 'Approved for FC review'), ('Decision Made', 'Decision Made'), ('Withdrawn', 'Withdrawn'), ('Closed', 'Closed')], default='In Progress', max_length=30)),
                ('misc_info', models.JSONField(blank=True, null=True)),
                ('highschool_info', models.JSONField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('highschool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createdon'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('associated_with', models.JSONField(blank=True, null=True)),
                ('upload', models.FileField(blank=True, storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.teacher_app_upload_path)),
                ('teacher_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructor_app.teacherapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantSchoolCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('misc_info', models.JSONField()),
                ('status', models.CharField(choices=[('---', '---'), ('Accepted', 'Accepted'), ('Conditionally Accepted', 'Conditionally Accepted'), ('Denied', 'Denied')], default='---', max_length=50)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.course')),
                ('highschool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.highschool')),
                ('starting_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cis.academicyear')),
                ('teacherapplication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructor_app.teacherapplication')),
            ],
            options={
                'unique_together': {('teacherapplication', 'course', 'highschool')},
            },
        ),
        migrations.CreateModel(
            name='ApplicantRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_on', models.DateField(auto_now=True)),
                ('recommendation', models.JSONField(blank=True, null=True)),
                ('submitter', models.JSONField(blank=True, null=True)),
                ('upload', models.FileField(storage=cis.storage_backend.PrivateMediaStorage(), upload_to=cis.utils.recommendation_upload_path)),
                ('applicantschoolcourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instructor_app.applicantschoolcourse')),
                ('teacher_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructor_app.teacherapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantCourseReviewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('---', '---'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Need more information', 'Need more information')], default='---', max_length=50)),
                ('misc_info', models.JSONField(blank=True, null=True)),
                ('status_changed_on', models.JSONField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructor_app.applicantschoolcourse')),
            ],
            options={
                'unique_together': {('reviewer', 'application_course')},
            },
        ),
    ]
