# Generated by Django 5.2.12 on 2026-03-25 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0027_customuser_last_updated_on_student_last_updated_on_and_more'),
        ('instructor_app', '0002_rename_fc_review_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantcoursereviewer',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inst_app_applicantcoursereviewer_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicantschoolcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inst_app_applicantschoolcourse_set', to='cis.course'),
        ),
        migrations.AlterField(
            model_name='applicantschoolcourse',
            name='highschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inst_app_applicantschoolcourse_set', to='cis.highschool'),
        ),
        migrations.AlterField(
            model_name='applicantschoolcourse',
            name='starting_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inst_app_applicantschoolcourse_set', to='cis.academicyear'),
        ),
        migrations.AlterField(
            model_name='teacherapplicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inst_app_teacherapplicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inst_app_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='highschool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inst_app_teacherapplication_set', to='cis.highschool'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inst_app_teacherapplication_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
