# Generated by Django 5.2.12 on 2026-03-31 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_app', '0003_alter_applicantcoursereviewer_reviewer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplicationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('parent', models.UUIDField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inst_app_notes', to=settings.AUTH_USER_MODEL)),
                ('teacher_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='instructor_app.teacherapplication')),
            ],
            options={
                'ordering': ['-createdon'],
            },
        ),
    ]
