# Generated by Django 5.2.14 on 2026-05-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_app', '0005_alter_teacherapplicationnote_createdby_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplicant',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
